### ISSUE TITLE
[Anon] Bug report: Fantasy Battles The 9th Age 2.0 Beta.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/The-9th-Age#232] opened 2019-02-12 21:38 UTC
**File:** Fantasy Battles The 9th Age 2.0 Beta.gstz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** Vermin swarm: if you chose to have Vermin Daemon on your army, the tunnel gunner limit must be reduced to 25% instead of 30%. This limit isn't correct now.

**Comment by DarkSkyT9A** [comment] 2019-05-03 19:03
This is a duplicate of issue #233 
Please close as such @Arturius1

**Closed** 2019-05-06 11:40 UTC
